version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    command: ["redis-server"]

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis
    command: >
      bash -c "
        uvicorn app.main:app --host 0.0.0.0 --port ${APP_PORT}
      "
    ports:
      - "${APP_PORT}:${APP_PORT}"

volumes:
  redis-data:
